[package]
name = "lazy-static-example"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
lazy_static = { path = "../lazy-static" }
regex = "1"
