[package]
name = "synom"
version = "0.12.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Stripped-down Nom parser used by Syn"
repository = "https://github.com/dtolnay/syn"
documentation = "https://docs.rs/synom/"
categories = ["development-tools::procedural-macro-helpers"]
readme = "../README.md"
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]

[dependencies]
proc-macro2 = { git = "https://github.com/mystor/proc-macro2", branch = "byte_literal" }

[dev-dependencies.syn]
version = "0.12"
path = ".."
features = ["parsing", "full"]
default-features = false
